alleyinteractive/alley-scripts

- package-lock.json
- package.json
- packages/eslint-config/CHANGELOG.md
- packages/eslint-config/package.json
- packages/eslint-config/typescript-react/index.js
To ensure files are published the eslint-config needs to be bumped as a patch version.
> Bump ESLint package version for publishing

- package-lock.json
- packages/eslint-config/CHANGELOG.md
- packages/eslint-config/package.json
- packages/eslint-config/typescript-react/index.js
Reorder ESLint extends in `/typescript-react` to ensure proper rules are followed.
This prevents and error where import/extensions don't support `.ts` files.
> Reorder ESLint extends for typescript-react config

- packages/create-block/templates/javascript/render.php.mustache
- packages/create-block/templates/typescript/render.php.mustache
This PR adds PHPCS Disable comments to disabled the `WordPress.NamingConventions.PrefixAllGlobals.NonPrefixedVariableFound` sniff in the `render.php` template.
This file is loaded outside of global scope, but PHPCS isn't aware of that.
> Ignore global scope sniff for Render files

- packages/create-entry/README.md
- packages/create-entry/src/entryArgs.ts
- packages/create-entry/templates/slotfill/index.php.mustache
This PR addresses the following in the `create-entry` package:
* Fixes a typo for a `wp_enqueue_script` parameter in a mustache template.
* Updates the slotfill description.
> AOS-40 - Update help description, fix enqueue param in template

- packages/block-editor-tools/src/components/media-picker/index.jsx
Avoids returning `Spinner` component when a previously selected media is deleted or can not be found. Renders the `MediaPlaceholder` so another media file can be picked.
https://github.com/alleyinteractive/alley-scripts/issues/43
> Spinner when selected image is deleted

- packages/block-editor-tools/src/components/media-picker/index.jsx
The name of this button is misleading since it doesn't open the dialog box so that an editor could replace the image but in fact, resets the image whereas the editor can either choose to add/choose a new one or not.
As a ESL speaker: Reset instead of Replace seems like a more appropriate name.
> Button: update misleading name

- package-lock.json
- packages/eslint-config/README.md
- packages/eslint-config/package.json
* Repairs `package.json` by removing duplicate dependencies
* Update dependencies to avoid the Typescript version warning for `@typescript-eslint`
```
=============
WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.
You may find that it works just fine, or you may not.
SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <5.1.0
YOUR TYPESCRIPT VERSION: 5.1.6
Please only submit bug reports when using the officially supported version.
=============
```
* Updates README with information about importing the appropriate resolver for Webpack.
> Update ESLint config dependencies and README.

- packages/block-editor-tools/src/hooks/use-block-name/README.md
- packages/block-editor-tools/src/hooks/use-block-name/index.js
- packages/block-editor-tools/src/hooks/use-parent-block/README.md
- packages/block-editor-tools/src/hooks/use-parent-block/index.js
- packages/block-editor-tools/src/hooks/use-parent-client-id/README.md
- packages/block-editor-tools/src/hooks/use-parent-client-id/index.js
- `useParentBlock` - Returns a block instead of the parent client ID.
- `useBlockName` - Get the name of the block using a client ID.
- `useParentClientId` - Get the client ID of a parent block.
- This might be a deprecated addition/fix. I'm not sure how people are using the `useParentBlock` but it doesn't return a block but a client id. 
- What about a different name for the client ID version? `useParentBlockID`? `ClientId` seems truer to the returned value.
> Add new `useBlocks` hooks and fixes the `useParentBlock` hook

- packages/block-editor-tools/package.json
- packages/block-editor-tools/src/components/post-picker/post-list.scss
When around less than 5 posts appear in the post picker modal, the items appear squished:
This change adds a width to the post picker list flex container so the items fit the container:
> PostPicker - Display flex items to fit container

- .github/workflows/ci.yml
- .github/workflows/phpcs.yml
- Eliminates unnecessary runs of CI checks on merge
- Prevents CI checks from running against draft PRs
- Eliminates the schedule for phpcs checks, which only applies to one component of this monorepo, in favor of using PR checks exclusively
> Only run GitHub Actions on non-draft PRs against main

- packages/eslint-config/CHANGELOG.md
- packages/eslint-config/package.json
- packages/eslint-config/typescript-react/index.js
Problem:
The following code throws a TypeScript error:
```tsx
return (
<div {...innerBlocksProps}>
<h2>Section Title Goes Here</h2>
{children}
</div>
);
```
The issue is with the `children` item, whereby TypeScript doesn't (and in this case, can't) know the shape of `children` and therefore throws the following error:
```
TS2322: Type  unknown  is not assignable to type  ReactNode
```
The recommended way of dealing with this is to wrap it in a fragment, like this:
```tsx
return (
<div {...innerBlocksProps}>
<h2>Section Title Goes Here</h2>
<>{children}</>
</div>
);
```
However, this causes ESLint to throw an error about a "useless fragment" in JSX, even though the fragment has a use in this case (specifically, TypeScript).
There is an option to allow a fragment when the fragment contains …
> Add allowExpressions for children in fragments in TS/React

- packages/create-block/package.json
- packages/create-block/templates/javascript/index.js.mustache
- packages/create-block/templates/typescript/index.ts.mustache
- block.json handles the aspects we care about during block registration, including `apiVersion` and `title`, so we don't need to include them in the TypeScript template (the JS template already works this way). This fixes an issue where the `apiVersion` parameter might not match between what is scaffolded here and what is in block.json (see the recent update from version 2 to 3).
- Eliminates the comment above the registration. It's clear what the function call is doing from its context and the comment isn't necessary.
> Let block registration flow from block.json

- packages/block-editor-tools/src/hooks/use-debounce/README.md
- packages/block-editor-tools/src/hooks/use-debounce/index.js
- packages/block-editor-tools/src/hooks/use-has-inner-blocks/README.md
- packages/block-editor-tools/src/hooks/use-inner-block-index/README.md
- packages/block-editor-tools/src/hooks/use-inner-blocks-attributes/README.md
- packages/block-editor-tools/src/hooks/use-inner-blocks-attributes/index.js
- packages/block-editor-tools/src/hooks/use-inner-blocks-count/README.md
- packages/block-editor-tools/src/hooks/use-inner-blocks/README.md
- packages/block-editor-tools/src/hooks/use-inner-blocks/index.js
- packages/block-editor-tools/src/hooks/use-parent-block-attributes/README.md
- packages/block-editor-tools/src/hooks/use-parent-block/index.js
- packages/block-editor-tools/src/hooks/use-post-by-id/README.md
- packages/block-editor-tools/src/hooks/use-post-by-id/index.js
- packages/block-editor-tools/src/hooks/use-post-meta-value/README.md
- packages/block-editor-tools/src/hooks/use-post-meta-value/index.js
- packages/block-editor-tools/src/hooks/use-post-meta/README.md
- packages/block-editor-tools/src/hooks/use-post/README.md
- packages/block-editor-tools/src/hooks/use-post/index.js
- packages/block-editor-tools/src/hooks/use-posts/README.md
- packages/block-editor-tools/src/hooks/use-terms/README.md
> Block Editor Tools: Misc updates

- package-lock.json
- packages/create-block/CHANGELOG.md
- packages/create-block/index.ts
- packages/create-block/package.json
Dependabot bumped Chalk to v5 after the release of v0.0.1, and the new version shipped with v0.0.2 yesterday, which introduced a breaking change due to Chalk v5 being incompatible with TypeScript. Chalk's maintainers advise using Chalk v4 "for now," but since Dependabot bumped the version to v5 due to a security issue, I'm removing Chalk altogether at this time to get this package working again. We can evaluate a path forward (either using Chalk or something else) in the future.
> Remove Dependency on Chalk

- .changeset/silly-planes-grow.md
- README.md
- packages/create-release/CHANGELOG.md
- packages/create-release/README.md
- packages/create-release/index.ts
- packages/create-release/src/entryArgs.ts
- packages/create-release/src/helpers.ts
The `composer.json`/`package.json` file should not be updated unless requested. This change is to make the version not primarily tracked in the `composer.json` file.
Related https://github.com/alleyinteractive/.github/pull/56
> Dont modify package.json/composer.json unless requested

- package-lock.json
- packages/eslint-config/package.json
This is a fix where the new directory "rules" was not added to the published files on npm.
> Add "rules" dir to published files in package.json

- package-lock.json
- packages/create-block/CHANGELOG.md
- packages/create-block/index.ts
- packages/create-block/package.json
- packages/create-block/tsconfig.json
Fixes #511 where the `alley-create-block` script is throwing an error about using an import statement outside of a module. 
This PR addresses this by ensuring that the Typescript compiler `module` and `moduleResolution` are set to NodeJS and Node. I believe the issue was introduced in 66dfdec from PR #480 where the `module` config rule was removed from the package `tsconfig.json` file.
This change adds the module config value back and changes the value to `nodenext` for modern versions of Node.js. The corresponding `moduleResolution` value was also added and when combined with the [module](https://www.typescriptlang.org/tsconfig#module) values, the TypeScript compiler will pick the right algorithm for each resolution based on whether Node.js will see an import or require in the output …
> Fixes alley-create-block compiler to ensure output is NodeJS compatible

- .changeset/chilly-hounds-repair.md
- package-lock.json
- packages/block-editor-tools/README.md
- packages/block-editor-tools/package.json
- packages/block-editor-tools/src/components/csv-uploader/README.md
- plugin/.eslintrc.json
- plugin/package.json
- plugin/tsconfig.eslint.json
Related to Issue #499
This PR adds all available components, hooks, and services READMEs to the root README so it can be accessible in the published NPM package.
Please refer to the example of WordPress package API docs here: https://github.com/WordPress/gutenberg/tree/trunk/packages/block-editor#api
https://github.com/alleyinteractive/alley-scripts/blob/c84cd840f1758f04c92c87729a7dc60e0723a3e7/packages/block-editor-tools/README.md
> Issue-499: block editor tools components, hooks, and services have incomplete documentation

- packages/scaffolder/__tests__/fixtures/sources/.scaffolder/config.yml
- packages/scaffolder/src/configuration/store.spec.ts
- packages/scaffolder/src/configuration/store.ts
- packages/scaffolder/src/features/store.spec.ts
- packages/scaffolder/src/features/store.ts
- packages/scaffolder/src/generators/generator.ts
Allows for packages to be installed that define their own scaffolder configuration. The use case here is to roll our scaffolder generations for most things (plugins/themes/etc.) into a standalone NPM package that isn't apart of `@alleyinteractive/scaffolder`.
Adds tests for both stores.
Fixes #551
> Allow scaffolder discovery from installed NPM modules

- .changeset/blue-papayas-flash.md
- package-lock.json
- plugin/README.md
- plugin/entries/slotfills/index.tsx
I would like to be able to run dev mode in any of the `alley-scripts/packages/*` while also running dev mode in the `alley-scripts/plugin` so that I can work on the scripts without having to run `npm run build` and refresh the page in order to see the changes.
Documentation also needs to be provided in order for developers to properly get set up to develop in the plugin accordingly.
Example:
In the directory `alley-scripts/packages/block-editor-tools` run `npm run dev` in the command line to run  Webpack development mode with the watch flag so that the files will recompile whenever they change. `webpack --mode=development --watch`.
Simultaneously in the `alley-scripts/plugin` directory I want to run `npm run dev` or `npm run start` while importing or linking with npm link the …
> Issue-582: Provide fast refresh when developing for scripts in package plugin

- .changeset/old-emus-destroy.md
- package-lock.json
- packages/create-block/index.ts
- packages/create-block/src/selectTemplates.ts
- packages/create-block/templates/javascript/view.js.mustache
- packages/create-block/templates/typescript/view.ts.mustache
The `wp-create-block` script from [@wordpress/create-block](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-create-block/) will scaffold a `viewScript` by default. This may not be necessary as many blocks do not require a view script. The result is that a stale file is scaffolded and enqueued when the developer creates a block. This may require the developer to manually remove the stale file and the block.json `viewScript` definition.
This change introduces a prompt allowing the developer to opt-in to including a [viewScript](https://developer.wordpress.org/block-editor/reference-guides/block-api/block-metadata/#view-script) block type definition and will scaffold with the scaffolded block by prompting the developer during the Alley create-block process. …
> Enhancement: Update `create-block` templates to scaffold optional view script

- packages/block-editor-tools/src/components/post-picker/post-list.scss
Per https://github.com/alleyinteractive/alley-scripts/issues/167:
No issues were found using the keyboard to navigate the current state of the PostPicker modal, however a subsequent Slack conversation surfaced that it's easy to overlook that a page has been selected. This PR slightly darkens that selected/hover state color, so that it's more noticeable without prompting a11y contrast concerns. (I picked this color to align with the hover states of WordPress core sidebar hover states.)
> darken hover/active state for PostPicker post list

- .changeset/tiny-carrots-cheat.md
- packages/tsconfig/README.md
- packages/tsconfig/base.json
Fixes #662
It's a common pattern to import from JSON files, which is supported by setting resolveJsonModule to true. We should add this to the tsconfig package as a default.
When developing Gutenberg blocks it's common to import block.json which fails out of the box with this config.
> Issue-662: Add resolveJsonModule to tsconfig

- packages/create-block/templates/javascript/index.php.mustache
- packages/create-block/templates/javascript/render.php.mustache
Handles direct requests gracefully. Exit silently rather than with a HTTP 500 error.
Closes https://github.com/alleyinteractive/alley-scripts/issues/671
> Prevent Direct Access to the Block's index.php file

- .changeset/slow-feet-tie.md
- packages/block-editor-tools/src/hooks/use-post-meta-value/README.md
- packages/block-editor-tools/src/hooks/use-post-meta-value/index.js
- packages/block-editor-tools/src/hooks/use-post-meta/README.md
- packages/block-editor-tools/src/hooks/use-post-meta/index.js
Allows `usePostMeta` and `usePostMetaValue` setter functions to accept a callable, which would accept the current meta value(s) and return updated values, similarly to how `useState()` works.
Resolves #674.
> Fix bug where post meta may not save

- .changeset/nine-ghosts-wink.md
- package-lock.json
- packages/build-tool/package.json
- packages/build-tool/tsconfig.json
Fixes an npm audit issue in `@wordpress/scripts`, too.
> Upgrading build-tool to WordPress 6.7

- .changeset/serious-nails-visit.md
- packages/tsconfig/base.json
Add `dist/` folder to the base tsconfig file `excludes` setting.
- Add `dist/` folder to the base tsconfig file `excludes` setting.
- Ensure that removing the default values does not affect the build and run-time behavior of projects using this configuration.
- Verify that the upgrade to the shared standard configuration is seamlessly integrated.
> Issue-665: Add dist folder to exclude config

- .changeset/tiny-coins-return.md
- packages/build-tool/package.json
Fixes #698
This pull request addresses the issue where importing the default Webpack config into an ESM project results in a build error due to missing type declarations. The changes ensure compatibility with ESM projects by providing the necessary type definitions and updating the package exports structure.
- Added type declarations for the Webpack config to support ESM projects.
- Updated the `exports` field in the `package.json` file for the `@alleyinteractive/build-tool` package to include:
- `types` fields pointing to the TypeScript declaration files for both CommonJS and ESM configurations.
- `default` fields pointing to the JavaScript implementation files.
- Revised the import/export structure to align with ESM standards.
1. Create a new ESM-based project.
2. Import the default …
> Issue-698: Webpack Config Types for ESM

- .changeset/strange-oranges-relate.md
- packages/block-editor-tools/src/components/post-picker/index.tsx
- packages/block-editor-tools/src/components/post-picker/post-list.scss
- packages/block-editor-tools/src/components/post-picker/post-list.tsx
- packages/block-editor-tools/src/components/post-picker/post.tsx
- packages/block-editor-tools/src/components/post-picker/search-modal.scss
- packages/block-editor-tools/src/components/post-picker/search-modal.tsx
- plugin/entries/slotfills/index.php
- plugin/entries/slotfills/index.tsx
- plugin/plugin.php
Fixes #675
This PR introduces an option to the PostPicker component to display using a "list" view type. This option allows for a more compact selection experience, with the grid view remaining as the default. Implementers can now choose to use the list view if they prefer.
This enhancement is particularly useful for users seeking a more compact post selection interface. By opting for the list view, the selection process becomes streamlined and potentially more user-friendly, depending on the specific implementation context.
1. Integrate the updated PostPicker into your project.
2. Verify that the PostPicker defaults to the modal view.
3. Opt-in to the `list` view by using the new `modalFormat` prop on the `PostPicker` component.
4. Test the list view to ensure it presents a compact and …
> Issue-675: Block Editor Tools: Add A List View Option to PostPicker

- .changeset/neat-pumas-yell.md
- packages/block-editor-tools/src/hooks/use-option/index.ts
- packages/block-editor-tools/src/hooks/use-post-meta-value/index.js
- packages/block-editor-tools/src/hooks/use-post-meta/index.js
- packages/block-editor-tools/src/hooks/use-terms/index.js
- **Memoize meta hook functions**
- **Memoize useOption callback functions**
- **Memoize useTerms callback**
Resolves #717
> Memoize functions returned by hooks

- .changeset/perfect-ways-bow.md
- packages/block-editor-tools/README.md
- packages/block-editor-tools/src/components/term-selector/index.tsx
This updates the `TermSelector` component to use the `FormTokenField` component from `@wordpress/components` to display term suggestions and currently selected terms.
This retains the `Selector` component in its current state and detaches the `TermSelector` from it. It's only being used by the deprecated `PostSelector`, so could be deprecated after this change is merged.
Addresses #809
> Issue-809: Display Selector options under the empty field

- .github/workflows/snapshot-release.yml
- README.md
Fixes #820 
Creates a new GH Action workflow that will publish a snapshot release to the `npm` registry for testing.
This is a new feature that I've not used before, but it seems very handy and would help in cross-package testing for certain scenarios.
1. Branch must begin with `snapshot`
2. Only runs via manual dispatch
3. A tag slug is required
> Create GH Action workflow for snapshot releases
